spring:
  application:
    name: worldmaphistory-backend
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/worldmaphistory?serverTimezone=UTC
    username: root
    password: root

logging:
  level:
    root: warn
