spring:
  application:
    name: worldmaphistory-backend
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    url: jdbc:mysql://localhost:3306/wmh
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: info
